; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nucleo_f303k8

[env:nucleo_f303k8]
platform = ststm32
board = nucleo_f303k8
framework = stm32cube
upload_protocol = stlink
upload_flags =
  -c
  set WORKAREASIZE 0x3000

build_flags =
  -Iinclude
  -Isrc
  -DSTM32F303x8

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
  +<services/uart_can_bridge_service.c>
  +<protocol/crc16_ccitt.c>
build_flags =
  -DSTM32F303x8
  -Iinclude
  -Ilib/Drivers/STM32F3xx_HAL_Driver/Inc
  -Ilib/Drivers/CMSIS/Device/ST/STM32F3xx/Include
  -Ilib/Drivers/CMSIS/Include
  -Wall
  -Wextra
  -Werror
