#ifndef KODENCHAN_BUTTON_CAN_TX_CONFIG_H
#define KODENCHAN_BUTTON_CAN_TX_CONFIG_H

#include "stm32f3xx_hal.h"

#include <stdint.h>

#define BUTTON_CAN_TX_POLL_PERIOD_MS 10U
#define BUTTON_CAN_TX_DEBOUNCE_MS 20U
#define BUTTON_CAN_TX_REPEAT_WHILE_PRESSED 1U
#define BUTTON_CAN_TX_REPEAT_PERIOD_MS 10U
#define BUTTON_CAN_TX_MODE_TOGGLE_HOLD_MS 1000U

/*
 * ボタンを押した時に送るCANフレーム設定
 *
 * 変更する場所:
 * - 送信先CAN ID: BUTTON_CAN_TX_PA0_STD_ID / BUTTON_CAN_TX_PA1_STD_ID
 * - 送信データ:   BUTTON_CAN_TX_PA0_DATA / BUTTON_CAN_TX_PA1_DATA
 *
 * 現在の設定:
 * - PA0を押す: JOINT1向け CAN ID 0x200, data = 00 00 00 00 FF FF 00 00
 * - PA1を押す: JOINT1向け CAN ID 0x200, data = 00 00 00 00 00 01 00 00
 *
 * 任意の8バイトを送りたい場合は BUTTON_CAN_TX_PA*_DATA の8個の値を直接書き換える。
 */
#define BUTTON_CAN_TX_PA0_STD_ID 0x200U
#define BUTTON_CAN_TX_PA0_DATA \
  {0x00U, 0x00U, 0x00U, 0x00U, 0xFFU, 0xFFU, 0x00U, 0x00U}

#define BUTTON_CAN_TX_PA1_STD_ID 0x200U
#define BUTTON_CAN_TX_PA1_DATA \
  {0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x01U, 0x00U, 0x00U}

#define BUTTON_CAN_TX_CONFIG_COUNT 2U
#define BUTTON_CAN_TX_CONFIGS \
  { \
    /* PA0が GPIO_PIN_RESET になったら BUTTON_CAN_TX_PA0_STD_ID / BUTTON_CAN_TX_PA0_DATA を送る。 */ \
    {GPIOA, GPIO_PIN_0, GPIO_PULLUP, GPIO_PIN_RESET, BUTTON_CAN_TX_PA0_STD_ID, BUTTON_CAN_TX_PA0_DATA}, \
    /* PA1が GPIO_PIN_RESET になったら BUTTON_CAN_TX_PA1_STD_ID / BUTTON_CAN_TX_PA1_DATA を送る。 */ \
    {GPIOA, GPIO_PIN_1, GPIO_PULLUP, GPIO_PIN_RESET, BUTTON_CAN_TX_PA1_STD_ID, BUTTON_CAN_TX_PA1_DATA} \
  }

#endif /* KODENCHAN_BUTTON_CAN_TX_CONFIG_H */
